/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/cabin.glb 
Author: Lukaas (https://sketchfab.com/Lukaas04)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cabin-b02b8de5e8374fa182d2561275177320
Title: Cabin
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cabin.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Loww_Poly_house2Mesh_initialShadingGroup_0.geometry} material={materials.initialShadingGroup} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/cabin.glb')
