/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/cat.glb 
Author: Alben Tan (https://sketchfab.com/albentan2012)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sleeping-cat-on-the-bed-1-3d-scan-ae07a741be6944e8ba5e2657069d3aaf
Title: Sleeping Cat On The Bed 1 - 3D scan
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cat.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material_0.006']} position={[-0.011, 0, -0.017]} rotation={[-Math.PI, 1.562, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/cat.glb')
